server:
  port: 39600
spring:
  application:
    name: mmc-order-service
  cloud:
    consul:
      host: 106.15.47.205
      port: 8500
      enabled: true
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        healthCheckInterval: 10s
        healthCheckTimeout: 10s
        healthCheckCriticalTimeout: 5s
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
